version: '3.3'

services:
  app:
    env_file:
      - .production.env
    container_name: app
    command: sh -c "npx fixtures -d test/fixtures -c ormconfig.prod.yml && npm run start:prod"
    restart: always
    build: .
    ports:
      - 3000:3000
    links:
      - db
    depends_on:
      - db
  db:
    image: postgres
    container_name: db
    restart: unless-stopped
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: eshop
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
