# Development fixture ORMConfig
default:
  type: 'postgres'
  host: 'localhost'
  port: 5432
  username: 'root'
  password: 'root'
  database: 'eshop'
  entities:
    - 'dist/**/*.entity{.ts,.js}'
  synchronize: false
  logging: true
