version: '3.3'

services:
  postgres:
    image: postgres
    container_name: postgres
    restart: unless-stopped
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: eshop
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root

  pgweb:
    container_name: pgweb
    restart: always
    image: sosedoff/pgweb
    ports:
      - '8081:8081'
    environment:
      - DATABASE_URL=postgres://root:root@postgres:5432/postgres?sslmode=disable
    depends_on:
      - postgres
