name: Deploy on push

on:
  push:
    branches:
      - 'develop'

jobs:
  build:
    name: Build and store /dist
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master

      - name: Install Dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Archive Production Artifact
        uses: actions/upload-artifact@master
        with:
          name: dist
          path: dist

  deploy-prod:
    name: Launch image to remote host
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Download compiled files
        uses: actions/download-artifact@v2
        with:
          name: dist
          path: dist

      - name: Set SSH key for remote host
        uses: webfactory/ssh-agent@v0.4.1
        with:
          ssh-private-key: ${{ secrets.DO_SSH_KEY }}

      - name: Create a docker context for remote machine
        run: docker context create digital_ocean --docker="host=${{secrets.DO_HOST}}"

      - name: Launch new configuration
        run: docker-compose --context digital_ocean -f docker-compose.prod.yml up -d --build --force-recreate

      - name: Logout from docker
        run: docker logout
